### ISSUE TITLE
is the Animajor data complete?

### ISSUE THREAD

**Issue by corpetty** [abhoward/abhoward.github.io#1]
I'm looking at doing some diggin at animajor stats, is the data in your assets folder complete or broken up based on the analysis you do?

It seems that OpenDota doesn't have it available anymore. 

Appreciate it.

**Comment by abhoward** [comment]
Whoa I didn't realize anyone was actually looking at this repo other than me. Very sorry for the delay!

To answer your question - the assets folder does not contain any data files, it's sole purpose is to host files that enrich the website; stuff like hero icons, team logos, css files, etc.

If you're referring to the data folder, it is broken down by each individual tournament. For example, there are subfolders for each TI10 qualifier, the Animajor, the ESL One tournament, etc. 

I hope that helps! Let me know if you have any further questions, otherwise I'll close this issue in the next couple of days.
